add dependency check functionality

diff --git a/writenow b/writenow
--- a/writenow
+++ b/writenow
@@ -1,4 +1,7 @@
 #!/bin/bash
+#
+# writenow - A simple bash script to write in edit-free mode
+#
 # Copyright (C) 2023  Salar Nosrati-Ershad
 #
 # This program is free software: you can redistribute it and/or modify
@@ -12,3 +15,25 @@
 # 
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <https://www.gnu.org/licenses/>.
+
+# Raise error on stderr
+# Arguments: error message
+# Output: error message on stderr
+function err() {
+  echo "Error: $*" >&2
+}
+
+# Check if a dependency is installed
+# Arguments: dependency name
+# Output: error message on stderr and exit if dependency is not installed
+# Return: 0 if dependency is installed, 1 otherwise
+function check_dependency() {
+  if ! command -v "$1" > /dev/null; then
+    err "dependency not found" "$1"
+    exit 0
+  fi
+}
+
+# Check dependencies
+# Busybox dependencies are not checked
+check_dependency "tput"
