add usage, version and arg parsing

diff --git a/writenow b/writenow
--- a/writenow
+++ b/writenow
@@ -16,6 +16,8 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <https://www.gnu.org/licenses/>.
 
+readonly VERSION="v0.0.1"
+
 # Raise error on stderr
 # Arguments: error message
 # Output: error message on stderr
@@ -23,17 +25,72 @@ function err() {
   echo "Error: $*" >&2
 }
 
-# Check if a dependency is installed
+# Show version information
+# Globals: VERSION
+# Output: version information on stdout
+function version() {
+  echo "writenow ${VERSION}"
+  echo "Copyright (C)  2023 Salar Nosrati-Ershad"
+  echo "License GPLv3: GNU GPL version 3 <https://gnu.org/licenses/gpl.html>"
+  echo "This is free software: you are free to change and redistribute it."
+  echo "There is NO WARRANTY, to the extent permitted by law."
+}
+
+# Show usage information
+# Output: usage and version information on stdout
+function usage() {
+  version
+  echo
+  echo "Usage: writenow [OPTION]..."
+  echo
+  echo "  -h, --help      display this help and exit"
+  echo "  -v, --version   display version information and exit"
+}
+
+# Parse arguments
+# Arguments: first arguments
+# Output: error message on stderr and exit if arguments are invalid
+# Return: 0 if arguments are valid, 1 otherwise
+function parse_args() {
+  case "$1" in
+    -h|--help)
+      usage
+      exit 0
+      ;;
+    -v|--version)
+      version
+      exit 0
+      ;;
+    *)
+      err "invalid argument:" "$1"
+      usage
+      exit 1
+      ;;
+  esac
+}
+
+# Check if a dependency is exist
 # Arguments: dependency name
 # Output: error message on stderr and exit if dependency is not installed
 # Return: 0 if dependency is installed, 1 otherwise
 function check_dependency() {
   if ! command -v "$1" > /dev/null; then
-    err "dependency not found" "$1"
+    err "dependency not found:" "$1"
     exit 0
   fi
 }
 
-# Check dependencies
-# Busybox dependencies are not checked
-check_dependency "tput"
+# Main function
+function main() {
+  # parse arguments
+  if [[ $# -gt 0 ]]; then
+    parse_args "$1"
+  fi
+
+  # Check dependencies
+  # Busybox dependencies are not checked
+  check_dependency "tput" # part of ncurses
+}
+
+
+main "$@"
